name: Daily Trading Signal Bot

on:
  schedule:
    - cron: "0 0 * * *"   # daily (adjust if needed)
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Run trading signal bot
        run: npm start
        env:
          TELEGRAM_BOT_TOKEN: "8487286204:AAE8lTujI3uGWA5kiFuTbIDqXuFmr3JhxHc"
          TELEGRAM_CHAT_ID: "8073791822"


      - name: Commit updated state.json
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add src/state/state.json
          git diff --cached --quiet || git commit -m "Update bot state"
          git push
